### ISSUE TITLE
Delete volumes of instances when de-scaling

### ISSUE THREAD

**Issue by DiegoRBaquero** [lserman/capistrano-elbas#25]
How could I achieve this?

I'm left with many volumes that I'd like deleted after the instances are terminated.

Thank you

**Comment by lserman** [comment]
ELBAS, at least in the later versions, will remove snapshots of previously made AMIs. Is that what you're referring to? If you just mean instances are terminated by AWS because of their AutoScaling so you have an image left over, that seems like it's outside the scope of this gem. ELBAS should clean itself up pretty well and only keep around the most recent copy of your AMI and snapshots.

**Comment by DiegoRBaquero** [comment]
I was referring to the EC2 instances' volumes (disk). Seems like volumes are/were created without the flag to be deleted when the instance is deleted.

I no longer use this, or ruby at all, so I wouldn't know if it's still an issue.
